### ISSUE TITLE
Operating System or Platform?

### ISSUE THREAD

**Issue by noloader** [w3c-webmob/installable-webapps#46]
Reference "Installable Web Apps", http://w3c-webmob.github.io/installable-webapps/.

From the Introduction:

"...the web platform also lacks sufficient metadata for a Web application to be successfully integrated into an operating system in the same way native applications are (i.e., not just on the homescreen, but integration into other contexts such as the task switcher, privacy and security settings, etc.)."

I think "operating system" could be changed to "platform". The platform includes hardware, os, features and capabilities, etc. The os is usually discussed in a more narrow context, and the description does not appear to be speaking to the narrow context.

**Comment by marcoscaceres** [comment]
@noloader I agree. Good points.  You want to send a PR or I'm happy to make the change in a few days.

**Comment by noloader** [comment]
@marcoscaceres - well, I would probably tend to it at leisure since its nothing more than a suggestion. Creating a report seems like overkill.
